SELECT * FROM shopping_data
--1. which category generates highest revenue?
SELECT category,SUM(purchase_amount) AS highest_revenue
FROM shopping_data
Group BY category
Order BY highest_revenue DESC  --Electronics
--2. Are discounts actually increasing purchase value?
SELECT discount_applied,SUM(purchase_amount) AS Total_revenue,
AVG(purchase_amount) AS avg_revenue
FROM shopping_data
Group by discount_applied --Discounts reduce profit
--3. What is the total revenue generated by male and female customers?
SELECT gender,SUM(purchase_amount) AS highest_revenue
FROM shopping_data
Group BY gender
Order BY highest_revenue DESC --Lack of understanding of revenue contribution by gender segments
--4. Which customer used a discount but still spent more than the average perchase amount?
SELECT 
customer_id,
purchase_amount,
discount_applied FROM shopping_data
WHERE discount_applied='Yes' AND purchase_amount > (SELECT AVG(purchase_amount)FROM shopping_data)
--Which are the top/bottom 5 products with the highest average review rating?
Select item_purchased,AVG(review_rating) AS Avg_ratings
FROM shopping_data
GROUP BY item_purchased
ORDER BY Avg_ratings ASC LIMIT 5;--Bottom 5
Select item_purchased,AVG(review_rating) AS Avg_ratings
FROM shopping_data
GROUP BY item_purchased
ORDER BY Avg_ratings DESC LIMIT 5;--Top 5
--6. Average purchase: Standard vs. Express Shipping
SELECT 
    shipping_type,
    COUNT(DISTINCT customer_id) AS order_placed,
    AVG(purchase_amount) AS avg_purchase,
    SUM(purchase_amount) AS revenue
FROM shopping_data
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type
ORDER BY revenue DESC;--unclear if faster shipping leads to higher spending
--7. Do subscribed customers spend more? Compare total revenue and average revenue between subscribers and non-subscribers
SELECT subscription_status,
AVG(purchase_amount) as avg_revenue, 
Sum(purchase_amount) as total_revenue
FROM shopping_data
Group by subscription_status
ORDER BY total_revenue DESC --Effect of subscription program
--8. Top 5 products with highest discount usage
SELECT item_purchased,
COUNT(item_purchased) as total_no_of_times_sold,
Count(CASE WHEN discount_applied='Yes' THEN 1 END) AS no_of_times_sold_when_discount_applied,
Count(CASE WHEN discount_applied='Yes' THEN 1 END)*100.0/COUNT(*) as percentage
FROM shopping_data
Group by item_purchased
ORDER BY percentage DESC limit 5;
--9. Segment customers into new, returning, loyal based on the no. of their previous purchases, and show the count of each segment
SELECT
CASE
WHEN previous_purchases='0' THEN 'New Customer'
WHEN previous_purchases BETWEEN 1 and 15 THEN 'Returning Customer'
Else 'Loyal Customer'
END AS customer_segment,
Count(*) as customer_count
FROM shopping_data
Group by CASE
WHEN previous_purchases='0' THEN 'New Customer'
WHEN previous_purchases BETWEEN 1 and 15 THEN 'Returning Customer'
Else 'Loyal Customer'
END
--10. What are the top 3 most purchased products within each category
With CTE as
(SELECT category, item_purchased,
Count(item_purchased) as most_purchased,
RANK() OVER(partition by category order by count(item_purchased)DESC) as RNK
FROM shopping_data
Group by category,item_purchased
)
SELECT * from CTE 
Where RNK<=3
--11. Are customers who are repeat buyers (More than 5 previous purchases) also likely to subscribe?
SELECT
CASE
WHEN previous_purchases>5 THEN 'Repeat Buyers'
ELSE 'Normal Buyers'
END as customer_type,
subscription_status,
Count(*) as customer_count,
Count(*) * 100.0/SUM(COUNT(*)) over(
Partition by CASE WHEN previous_purchases>5 THEN 'Repeat Buyers'
ELSE 'Normal Buyers'
END
)As percents
FROM shopping_data
Group by CASE
WHEN previous_purchases>5 THEN 'Repeat Buyers'
ELSE 'Normal Buyers'
END,subscription_status
--12. What is the revenue contribution of each age group?
select
case
when age between 18 and 25 then '18-25'
when age between 26 and 35 then '26-35'
when age between 36 and 50 then '36-50'
else '51+'
end as age_group,
sum(purchase_amount) as total_revenue
FROM shopping_data
Group by case
when age between 18 and 25 then '18-25'
when age between 26 and 35 then '26-35'
when age between 36 and 50 then '36-50'
else '51+'
end
Order by total_revenue DESC